//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appson.Common.General.Text {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NumericStringUtilsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NumericStringUtilsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Appson.Common.General.Text.NumericStringUtilsResources", typeof(NumericStringUtilsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفر.
        /// </summary>
        public static string CardinalTextual0 {
            get {
                return ResourceManager.GetString("CardinalTextual0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک.
        /// </summary>
        public static string CardinalTextual1 {
            get {
                return ResourceManager.GetString("CardinalTextual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ده.
        /// </summary>
        public static string CardinalTextual10 {
            get {
                return ResourceManager.GetString("CardinalTextual10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صد.
        /// </summary>
        public static string CardinalTextual100 {
            get {
                return ResourceManager.GetString("CardinalTextual100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزار.
        /// </summary>
        public static string CardinalTextual1000 {
            get {
                return ResourceManager.GetString("CardinalTextual1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یازده.
        /// </summary>
        public static string CardinalTextual11 {
            get {
                return ResourceManager.GetString("CardinalTextual11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوازده.
        /// </summary>
        public static string CardinalTextual12 {
            get {
                return ResourceManager.GetString("CardinalTextual12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیزده.
        /// </summary>
        public static string CardinalTextual13 {
            get {
                return ResourceManager.GetString("CardinalTextual13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارده.
        /// </summary>
        public static string CardinalTextual14 {
            get {
                return ResourceManager.GetString("CardinalTextual14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانزده.
        /// </summary>
        public static string CardinalTextual15 {
            get {
                return ResourceManager.GetString("CardinalTextual15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شانزده.
        /// </summary>
        public static string CardinalTextual16 {
            get {
                return ResourceManager.GetString("CardinalTextual16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفده.
        /// </summary>
        public static string CardinalTextual17 {
            get {
                return ResourceManager.GetString("CardinalTextual17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجده.
        /// </summary>
        public static string CardinalTextual18 {
            get {
                return ResourceManager.GetString("CardinalTextual18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوزده.
        /// </summary>
        public static string CardinalTextual19 {
            get {
                return ResourceManager.GetString("CardinalTextual19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دو.
        /// </summary>
        public static string CardinalTextual2 {
            get {
                return ResourceManager.GetString("CardinalTextual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیست.
        /// </summary>
        public static string CardinalTextual20 {
            get {
                return ResourceManager.GetString("CardinalTextual20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دویست.
        /// </summary>
        public static string CardinalTextual200 {
            get {
                return ResourceManager.GetString("CardinalTextual200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه.
        /// </summary>
        public static string CardinalTextual3 {
            get {
                return ResourceManager.GetString("CardinalTextual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سی.
        /// </summary>
        public static string CardinalTextual30 {
            get {
                return ResourceManager.GetString("CardinalTextual30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیصد.
        /// </summary>
        public static string CardinalTextual300 {
            get {
                return ResourceManager.GetString("CardinalTextual300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهار.
        /// </summary>
        public static string CardinalTextual4 {
            get {
                return ResourceManager.GetString("CardinalTextual4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهل.
        /// </summary>
        public static string CardinalTextual40 {
            get {
                return ResourceManager.GetString("CardinalTextual40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارصد.
        /// </summary>
        public static string CardinalTextual400 {
            get {
                return ResourceManager.GetString("CardinalTextual400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج.
        /// </summary>
        public static string CardinalTextual5 {
            get {
                return ResourceManager.GetString("CardinalTextual5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجاه.
        /// </summary>
        public static string CardinalTextual50 {
            get {
                return ResourceManager.GetString("CardinalTextual50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانصد.
        /// </summary>
        public static string CardinalTextual500 {
            get {
                return ResourceManager.GetString("CardinalTextual500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شش.
        /// </summary>
        public static string CardinalTextual6 {
            get {
                return ResourceManager.GetString("CardinalTextual6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شصت.
        /// </summary>
        public static string CardinalTextual60 {
            get {
                return ResourceManager.GetString("CardinalTextual60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ششصد.
        /// </summary>
        public static string CardinalTextual600 {
            get {
                return ResourceManager.GetString("CardinalTextual600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفت.
        /// </summary>
        public static string CardinalTextual7 {
            get {
                return ResourceManager.GetString("CardinalTextual7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتاد.
        /// </summary>
        public static string CardinalTextual70 {
            get {
                return ResourceManager.GetString("CardinalTextual70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتصد.
        /// </summary>
        public static string CardinalTextual700 {
            get {
                return ResourceManager.GetString("CardinalTextual700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشت.
        /// </summary>
        public static string CardinalTextual8 {
            get {
                return ResourceManager.GetString("CardinalTextual8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتاد.
        /// </summary>
        public static string CardinalTextual80 {
            get {
                return ResourceManager.GetString("CardinalTextual80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتصد.
        /// </summary>
        public static string CardinalTextual800 {
            get {
                return ResourceManager.GetString("CardinalTextual800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نه.
        /// </summary>
        public static string CardinalTextual9 {
            get {
                return ResourceManager.GetString("CardinalTextual9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نود.
        /// </summary>
        public static string CardinalTextual90 {
            get {
                return ResourceManager.GetString("CardinalTextual90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهصد.
        /// </summary>
        public static string CardinalTextual900 {
            get {
                return ResourceManager.GetString("CardinalTextual900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اول.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ام.
        /// </summary>
        public static string GenericOrdinalFormat {
            get {
                return ResourceManager.GetString("GenericOrdinalFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.##} میلیارد.
        /// </summary>
        public static string NumericBillions {
            get {
                return ResourceManager.GetString("NumericBillions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.##} میلیون.
        /// </summary>
        public static string NumericMillions {
            get {
                return ResourceManager.GetString("NumericMillions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.##}.
        /// </summary>
        public static string NumericOnes {
            get {
                return ResourceManager.GetString("NumericOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:#.##} هزار.
        /// </summary>
        public static string NumericThousands {
            get {
                return ResourceManager.GetString("NumericThousands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفرم.
        /// </summary>
        public static string OrdinalTextual0 {
            get {
                return ResourceManager.GetString("OrdinalTextual0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکم.
        /// </summary>
        public static string OrdinalTextual1 {
            get {
                return ResourceManager.GetString("OrdinalTextual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دهم.
        /// </summary>
        public static string OrdinalTextual10 {
            get {
                return ResourceManager.GetString("OrdinalTextual10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صدم.
        /// </summary>
        public static string OrdinalTextual100 {
            get {
                return ResourceManager.GetString("OrdinalTextual100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزارم.
        /// </summary>
        public static string OrdinalTextual1000 {
            get {
                return ResourceManager.GetString("OrdinalTextual1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یازدهم.
        /// </summary>
        public static string OrdinalTextual11 {
            get {
                return ResourceManager.GetString("OrdinalTextual11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوازدهم.
        /// </summary>
        public static string OrdinalTextual12 {
            get {
                return ResourceManager.GetString("OrdinalTextual12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیزدهم.
        /// </summary>
        public static string OrdinalTextual13 {
            get {
                return ResourceManager.GetString("OrdinalTextual13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهاردهم.
        /// </summary>
        public static string OrdinalTextual14 {
            get {
                return ResourceManager.GetString("OrdinalTextual14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانزدهم.
        /// </summary>
        public static string OrdinalTextual15 {
            get {
                return ResourceManager.GetString("OrdinalTextual15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شانزدهم.
        /// </summary>
        public static string OrdinalTextual16 {
            get {
                return ResourceManager.GetString("OrdinalTextual16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفدهم.
        /// </summary>
        public static string OrdinalTextual17 {
            get {
                return ResourceManager.GetString("OrdinalTextual17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هجدهم.
        /// </summary>
        public static string OrdinalTextual18 {
            get {
                return ResourceManager.GetString("OrdinalTextual18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوزدهم.
        /// </summary>
        public static string OrdinalTextual19 {
            get {
                return ResourceManager.GetString("OrdinalTextual19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوم.
        /// </summary>
        public static string OrdinalTextual2 {
            get {
                return ResourceManager.GetString("OrdinalTextual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیستم.
        /// </summary>
        public static string OrdinalTextual20 {
            get {
                return ResourceManager.GetString("OrdinalTextual20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دویستم.
        /// </summary>
        public static string OrdinalTextual200 {
            get {
                return ResourceManager.GetString("OrdinalTextual200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوم.
        /// </summary>
        public static string OrdinalTextual3 {
            get {
                return ResourceManager.GetString("OrdinalTextual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سی ام.
        /// </summary>
        public static string OrdinalTextual30 {
            get {
                return ResourceManager.GetString("OrdinalTextual30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیصدم.
        /// </summary>
        public static string OrdinalTextual300 {
            get {
                return ResourceManager.GetString("OrdinalTextual300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارم.
        /// </summary>
        public static string OrdinalTextual4 {
            get {
                return ResourceManager.GetString("OrdinalTextual4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهلم.
        /// </summary>
        public static string OrdinalTextual40 {
            get {
                return ResourceManager.GetString("OrdinalTextual40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارصدم.
        /// </summary>
        public static string OrdinalTextual400 {
            get {
                return ResourceManager.GetString("OrdinalTextual400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجم.
        /// </summary>
        public static string OrdinalTextual5 {
            get {
                return ResourceManager.GetString("OrdinalTextual5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجاهم.
        /// </summary>
        public static string OrdinalTextual50 {
            get {
                return ResourceManager.GetString("OrdinalTextual50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانصدم.
        /// </summary>
        public static string OrdinalTextual500 {
            get {
                return ResourceManager.GetString("OrdinalTextual500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ششم.
        /// </summary>
        public static string OrdinalTextual6 {
            get {
                return ResourceManager.GetString("OrdinalTextual6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شصتم.
        /// </summary>
        public static string OrdinalTextual60 {
            get {
                return ResourceManager.GetString("OrdinalTextual60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ششصدم.
        /// </summary>
        public static string OrdinalTextual600 {
            get {
                return ResourceManager.GetString("OrdinalTextual600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتم.
        /// </summary>
        public static string OrdinalTextual7 {
            get {
                return ResourceManager.GetString("OrdinalTextual7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتادم.
        /// </summary>
        public static string OrdinalTextual70 {
            get {
                return ResourceManager.GetString("OrdinalTextual70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتصدم.
        /// </summary>
        public static string OrdinalTextual700 {
            get {
                return ResourceManager.GetString("OrdinalTextual700", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتم.
        /// </summary>
        public static string OrdinalTextual8 {
            get {
                return ResourceManager.GetString("OrdinalTextual8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتادم.
        /// </summary>
        public static string OrdinalTextual80 {
            get {
                return ResourceManager.GetString("OrdinalTextual80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشتصدم.
        /// </summary>
        public static string OrdinalTextual800 {
            get {
                return ResourceManager.GetString("OrdinalTextual800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهم.
        /// </summary>
        public static string OrdinalTextual9 {
            get {
                return ResourceManager.GetString("OrdinalTextual9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نودم.
        /// </summary>
        public static string OrdinalTextual90 {
            get {
                return ResourceManager.GetString("OrdinalTextual90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهصدم.
        /// </summary>
        public static string OrdinalTextual900 {
            get {
                return ResourceManager.GetString("OrdinalTextual900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  و .
        /// </summary>
        public static string TextualJointer {
            get {
                return ResourceManager.GetString("TextualJointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منهای {0}.
        /// </summary>
        public static string TextualNegativeFormat {
            get {
                return ResourceManager.GetString("TextualNegativeFormat", resourceCulture);
            }
        }
    }
}
